#:kivy 1.1.0

MainWindow:
    BoxLayout:
        id: main_layout
        orientation: 'horizontal'
        padding: [10,10,10,10]
        spacing: 20
        BoxLayout:
            id: left_box
            orientation: 'vertical'
            size_hint_x: 0.6
            BoxLayout:
                id: change_buttons
                size_hint_y: 0.1
                orientation: 'horizontal'
                Button:
                    id: prev_button
                    text: 'Hacia atras'
                    on_release: app.prev_section()
                Label:
                    id: catalog_label
                    text: 'Catálogo de partes'
                Button:
                    id: next_button
                    text: 'Hacia adelante'
                    on_release: app.next_section()
            ScrollView:
                id: scrollview
                size_hint_y: 0.8
                do_scroll_x: False
                do_scroll_y: True
            BoxLayout:
                size_hint_y: 0.1
                orientation: 'horizontal'
                Label:
                    text:'Hombre'
                CheckBox:
                    id: cb_hombre
                    group: 'genero'
                    on_active: app.change_genre()
                Label:
                    text:'Mujer'
                CheckBox:
                    id: cb_mujer
                    group: 'genero'
                    on_active: app.change_genre()


        BoxLayout:
            id: right_box
            orientation: 'vertical'
            size_hint_x: 0.4
            Image:
                id: build_image
                size_hint_y: 0.7
                source: 'images/no-image.jpg'
                fit_mode: "contain"
            ScrollView:
                size_hint_y: 0.2
                do_scroll_x: False
                do_scroll_y: True
                bar_width: dp(10)
                Label:
                    id: messages
                    size_hint_y: None
                    height: self.texture_size[1] + dp(20)
                    text_size: self.width - dp(20), None
                    halign: 'left'
                    valign: 'top'
                    font_size: dp(11)
                    text: "Bienvenido"
                    padding: dp(10), dp(10)
            BoxLayout:
                orientation: 'horizontal'
                size_hint_y: 0.1
                Button:
                    id: reset
                    text: "Reset"
                    on_release: app.reset_app()
                Button
                    id: fin
                    text: "Guardar Finalizar"
                    on_press: app.save_image()